### ISSUE TITLE
Identity plus sparse matrix changes Ti

### ISSUE THREAD

**Issue by SobhanMP** [JuliaSparse/SparseArrays.jl#103]
```julia
using SparseArrays, LinearAlgebra
A = spzeros(Float64, Int32, 100, 100)
B = I - A
@assert typeof(A) == typeof(B)
```
fails since B is a `SparseMatrixCSC{Float64, Int64}`

**Comment by SobhanMP** [comment]
maybe making size return Ti and sparse of Ti return sparse matrices of type Ti would be the solution? i this legal?

**Comment by SobhanMP** [comment]
at least i think 
```
sparse(::Type{Tv}, s::UniformScaling, m::Integer, n::Integer) where {Tv, Ti} = SparseMatrixCSC{Tv}(s, Dims((m, n)))
sparse(::Type{Tv}, ::Type{Ti}, s::UniformScaling, m::Integer, n::Integer) where {Tv, Ti} = SparseMatrixCSC{Tv, Ti}(s, Dims((m, n)))
```
should be added

**Comment by ViralBShah** [comment]
Seems reasonable.

**Comment by ViralBShah** [comment]
@SobhanMP Have invited  you to the JuliaSparse org. Once you accept, I'll add you to this repo. Thanks for the amazing contributions, and hopefully repo access makes it a bit easier. Of course, still use PRs and reviews and all the same processes for getting changes in.

**Comment by SobhanMP** [comment]
thanks! will do
