### ISSUE TITLE
Cannot solve Ax = B for sparse matrices A, B

### ISSUE THREAD

**Issue by lzxnl** [JuliaSparse/SparseArrays.jl#117]
A\B works if A is a sparse matrix and B is a sparse vector. A\B does not work if B is a sparse matrix.

Example:
```
using SparseArrays, LinearAlgebra
A = sparse(I,100,100)
B = sparse(I,100,100)
C = sprandn(100,0.5)
A\B # will fail 
A\C # will work. 
```

Sometimes I can get around this by dividing column by column, but it's nevertheless still a strange bug to have.

**Comment by ViralBShah** [comment]
This works now.
