### ISSUE TITLE
Performance issue with (sparse) backsolve after LU factorization (turn off iterative refinement by default)

### ISSUE THREAD

**Issue by briochemc** [JuliaSparse/SparseArrays.jl#122]
I noticed there was a performance issue with the backsolve that I thought I should share here. 

Coming from MATLAB I thought the best way to show this performance issue was to benchmark the two on the same machine with the same data, so here it is. I perform a simple backslash (`M \ x`), a factorization (`factorize(M)`), and two backsolves (`Mf \ x` and `Mf \ [x 2x 3x 4x]`) using a somewhat-random matrix `M` and vector `x`. First, I use MATLAB (v2017b) to perform this test and I save `M` and `x` in a `.mat` file. Finally I load these in Julia (v1.1.0) using the MAT.jl package and perform the same test again. (I `] up`'d my packages before this test.)

Here are the results (the code I used is at the end of this post):
1. MATLAB performance:
    ```matlab
    >> tic; Mf = linfactor(M); toc;
    Elapsed time is 45.817367 seconds.
    >> tic; M \ x; toc;
    Elapsed time is 34.809706 seconds.
    >> tic; linfactor(Mf, x); toc;
    Elapsed time is 0.352151 seconds.
    >> tic; linfactor(Mf, [x 2*x 3*x 4*x]); toc;
    Elapsed time is 1.288229 seconds.
    ```

2. Julia performance:
    ```julia
    julia> @btime Mf = factorize(M) ;
      32.151 s (66 allocations: 8.71 GiB)
    
    julia> @btime M \ x ;
      33.191 s (74 allocations: 8.71 GiB)
    
    julia> @btime Mf \ x ;
      1.132 s (8 allocations: 1.22 MiB)
    
    julia> @btime Mf \ [x 2x 3x 4x] ;
      4.523 s (31 allocations: 5.95 MiB)
    ```

As you can see the backsolves in Julia take roughly 3–4 times as long as the MATLAB equivalent, while the factorization takes roughly the same time. Any idea what is the issue there? (Note using inplace `ldiv!` does not change those times).

(I know I am comparing apples to oranges, and that this could be an artefact of the random `M` and `x` but I seem to see this happen every time and I think there is too significant a difference in performance to be neglected. Please tell me if I am wrong 🙂)

----

The code I used:
1. MATLAB code:
    ```MATLAB
    n = 20000;
    M = sprand(n, n, 20/n) + speye(n);
    x = rand(n, 1);
    tic; Mf = linfactor(M); toc;
    tic; M \ x; toc;
    tic; linfactor(Mf, x); toc;
    tic; linfactor(Mf, [x 2*x 3*x 4*x]); toc;
    save test_matrix.mat M x
    ```

2. Julia code
    ```Julia
    using LinearAlgebra, SparseArrays, SuiteSparse, BenchmarkTools, MAT
    M = matread("test_matrix.mat")["M"] ;
    x = matread("test_matrix.mat")["x"] ;
    Mf = factorize(M) ;
    @btime Mf = factorize(M) ;
    @btime M \ x ;
    @btime Mf \ x ;
    @btime Mf \ [x 2x 3x 4x] ;
    ```

**Comment by ViralBShah** [comment]
@SobhanMP In your workspace sizing code, I noticed the comment that it could be smaller if iterative refinement is off. Would it be a huge gain?

We do want to turn off iterative refinement by default, but have a way to turn it on optionally.

**Comment by SobhanMP** [comment]
do you know why UMFPACK_IRSTEP isn't exported by the wrapper?

**Comment by ViralBShah** [comment]
Commit cda0c8ce disables iterative refinement.
