### ISSUE TITLE
Strange behavior of similar for sparse arrays

### ISSUE THREAD

**Issue by bkamins** [JuliaSparse/SparseArrays.jl#14]
We have the following:

```
julia> x = spzeros(1)
1-element SparseVector{Float64, Int64} with 0 stored entries

julia> similar(x)
1-element SparseVector{Float64, Int64} with 0 stored entries

julia> x[1] = 1
1

julia> x
1-element SparseVector{Float64, Int64} with 1 stored entry:
  [1]  =  1.0

julia> similar(x)
1-element SparseVector{Float64, Int64} with 1 stored entry:
  [1]  =  6.36599e-314
```

Which seems strange to me as `similar` should produce an uninitialized array, while in the second example it is initialized as I would consider sparse array uninitialized if it had 0 stored entries.

CC @nalimilan

**Comment by ViralBShah** [comment]
`similar` copies the structure and not the values. I feel what we do is reasonable. Perhaps this should be captured in the documentation.
