### ISSUE TITLE
transpose! allocates?

### ISSUE THREAD

**Issue by SobhanMP** [JuliaSparse/SparseArrays.jl#150]
```julia
julia> using SparseArrays, LinearAlgebra, BenchmarkTools
       let A = sprandn(100, 100, 0.1),
           X = deepcopy(A)
       
           @btime transpose!($X, $A)
           @time  transpose!(X, A)
           
           # @descend_code_warntype transpose!(X, A)
       end;


  1.229 μs (3 allocations: 128 bytes)
  0.000006 seconds (10 allocations: 368 bytes)
```
i was guessing type safety problems but couldn't find any other than size(A, 2) being any.
![Screenshot from 2022-06-21 12-14-01](https://user-images.githubusercontent.com/2301159/174849298-0f7d2c14-536d-4d87-9b14-cf8def30401c.png)

using @time i found that _distributevals_halfperm! is the culprit, not sure why.

**Comment by Wimmerer** [comment]
Why is `size` Any? I would think that's type stable Int64.

**Comment by SobhanMP** [comment]
i have no idea. Maybe it's a but warn_type. One solution would be to specialize everything in that chain on their functions. It makes sense since the default f is identity

**Comment by SobhanMP** [comment]
i.e. ```function halfperm!(X::AbstractSparseMatrixCSC{Tv,Ti}, A::AbstractSparseMatrixCSC{TvA,Ti},
        q::AbstractVector{<:Integer}, f::F = identity) where {Tv,TvA,Ti,F}```
