### ISSUE TITLE
Document GPL (and fix no longer valid links)

### ISSUE THREAD

**Issue by PallHaraldsson** [JuliaSparse/SparseArrays.jl#169]
SuiteSparse is (and will be GPL). It's not documented under:

```
help?> SuiteSparse
```

in my Julia 1.7.0 (after `using SuiteSparse`) doing the above I se e.g.:
```
  [docs-v1-img]: https://img.shields.io/badge/docs-v1-blue.svg [docs-v1-url]: https://julialang.github.io/SuiteSparse.jl/v1/
```

That link is no longer valid (can it be made to work again?), and the new working one is: https://docs.julialang.org/en/v1/stdlib/SuiteSparse/

For the future, it seems you will not do the above rather:

```
help?> SparseArrays
```

since those have been merged. Neither in the new SuiteSparse.jl (nor in SuiteSparse_jll), nor in this package's LICENCE file is GPL mentioned. I suggest it to be done, and in user-visible docs, especially since SparseArrays was previously MIT (only; now MIT + GPL, so this package "GPL as a whole").

Something like "since Julia 1.9 [right version?], SparseArrays is GPL-licenced" should be in docs (individual files can still be MIT). Going from MIT to GPL, might be surprising to many, sort of a "breaking" change (so mention in NEWS if not already done). I suppose most (not all?), would have been using the GPLed SuiteSparse anyway. But even some of those maybe unknowingly.

In general the help returns:

```
help?> SuiteSparse
search:

Couldn't find SuiteSparse
```

if you've not yet done using X. It might be a good idea in general (new issue at JuliaLang?), to allow searching the full docs.

**Comment by PallHaraldsson** [comment]
I think "The code in this repository is part of the Julia project. See the LICENSE file in the Julia project" in these two packages, isn't very helpful, especially for this one (or just wrong, since GPL will then not be found). There's no reason to point there (to MIT), unless you click yet again, just say "it's GPL"... is something to that effect.

**Comment by PallHaraldsson** [comment]
I thought it was policy, but I can't find it, so I made a PR. https://github.com/JuliaRegistries/General/pull/63230 I may only remember a discussion somewhere, may have been my own.

**Comment by SobhanMP** [comment]
but this repo doesn't contain suitesparse.

**Comment by SobhanMP** [comment]
also base contains `Base.USE_GPL_LIBS` and this package complies with it so i'm not sure what is it that you're looking for.

**Comment by ViralBShah** [comment]
@PallHaraldsson We are fine on all the licensing documentation. Please do not open issues and PRs related to that. For broken links, please open a separate issue.

Once this package is completely removed from base Julia, we can take whatever steps are necessary to better document the licensing situation then - but for now, we do not need to do anything.
