### ISSUE TITLE
CI: non-deterministic failure in SparseArrays/higherorderfns

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaSparse/SparseArrays.jl#178]
E.g. https://buildkite.com/julialang/julia-master/builds/13661#0181e2d2-87e0-4225-88a1-d953c29fce1f

```
Error in testset SparseArrays/higherorderfns:
Test Failed at /cache/build/default-amdci4-1/julialang/julia-master/julia-e750ba7d9a/share/julia/stdlib/v1.9/SparseArrays/test/higherorderfns.jl:25
Expression: #= /cache/build/default-amdci4-1/julialang/julia-master/julia-e750ba7d9a/share/julia/stdlib/v1.9/SparseArrays/test/higherorderfns.jl:25 =# @allocated(map!(sin, X, A)) == 0
Evaluated: 320 == 0
```

**Comment by ViralBShah** [comment]
Is this happening repeatedly?

**Comment by DilumAluthge** [comment]
I've seen it a couple different times, but it is pretty uncommon.

**Comment by SobhanMP** [comment]
this is my guess for the cause, non-structural zeros causes sparse(Array(A)) to not have the exact structure as A. tho i'm not having a lot of success making rand() generate zeros.
https://github.com/JuliaSparse/SparseArrays.jl/pull/199

**Comment by SobhanMP** [comment]
@DilumAluthge please open it again if it happens again.
