### ISSUE TITLE
umfpack config names are zero index but umf_ctrl is one indexed

### ISSUE THREAD

**Issue by SobhanMP** [JuliaSparse/SparseArrays.jl#180]
```julia
using SparseArrays
using SparseArrays: UMFPACK, LibSuiteSparse
UMFPACK.umf_ctrl[LibSuiteSparse.UMFPACK_IRSTEP + 1] # 2.0
```

since @ViralBShah  wants to set the default IRSTEP to zero. i think we have to address this. UMFPACK_IRSTEP (coming from the C library) is not the correct index to use in the library. Right now the "canonical" way of setting the config is to change `umf_ctrl` which loads the default configs from Umfpack. I think that having a plus one is weird. What would be a good interface for setting and getting it? should we make getters and setters? redefine the constants for julia? if we can figure out a right way of solving this. The rest is easy.

**Comment by ViralBShah** [comment]
Is redefining the constants easy? That will be the easiest path - but if they are coming automatically from C header file translation, that's not going to work.

**Comment by SobhanMP** [comment]
what i had in mind was defining  UMFPACKJ_IRSTEP = UMFPACK_IRSTEP + 1. yeah they are auto generated so not ideal

**Comment by ViralBShah** [comment]
How about `JL_UMFPACK_IRSTEP` to be clearer.

**Comment by SobhanMP** [comment]
TIL, `umfpack_report_numeric` doesn't work at all. and it's not tested, i guess i can fix it while i'm at it.

**Comment by ViralBShah** [comment]
Thanks for the long pending umfpack overhaul!
