### ISSUE TITLE
UMFPACK, CHOLMOD, and SPQR configuration audit

### ISSUE THREAD

**Issue by Gnimuc** [JuliaSparse/SparseArrays.jl#182]
We should audit the UMFPACK build and configuration to ensure those issues are not causing  https://github.com/JuliaSparse/SparseArrays.jl/issues/147

https://github.com/DrTimothyAldenDavis/SuiteSparse/blob/master/SuiteSparse_config/SuiteSparse_config.mk#L272
> -D'LONGBLAS=long' or -DLONGBLAS='long long' defines the integers used by LAPACK and the BLAS (defaults to 'int')

In the build script, we have:

https://github.com/JuliaPackaging/Yggdrasil/blob/cc75959bcf85b016625d9e528db277fd4d3b32d9/S/SuiteSparse/SuiteSparse/build_tarballs.jl#L37

In Clang.jl generator, we have:

https://github.com/JuliaSparse/SparseArrays.jl/blob/797406962fcf277615cbfc210491766657125cdd/gen/generator.jl#L48

We need to double-check these flags and make sure they are correctly and effectively configured.

[Updated by @ViralBShah to use Tim Davis' repo]

**Comment by Wimmerer** [comment]
Not sure whether this is an issue but we should be using https://github.com/DrTimothyAldenDavis/SuiteSparse now. I believe that's what we use in BB. That other repo is quite old.

**Comment by ViralBShah** [comment]
I had recently audited these flags, and concluded that they were correctly configured for win64. I believe if we got this wrong, we would have been seeing SuiteSparse crashes all over.

**Comment by ViralBShah** [comment]
[These comments in SuiteSparse_config.h](https://github.com/DrTimothyAldenDavis/SuiteSparse/blob/05b25d3fe446d51240faa2bd16f7187a561f10e9/SuiteSparse_config/SuiteSparse_config.h#L23) are also relevant.

**Comment by ViralBShah** [comment]
Our default BLAS on 64-bit is ILP64, which is why we use `-DLONGBLAS='long long'` on all 64-bit systems, and `SuiteSparse_long` also gets correctly picked up on Win64 as `long long`.

**Comment by ViralBShah** [comment]
I tried looking for places where SuiteSparse might expect `long` and receive `long long` on Windows or vice versa, but everything looked pretty consistent. Someone should look at it with fresh eyes.

**Comment by ViralBShah** [comment]
One other thought - is it possible that we are using freed memory somewhere - like something is getting finalized or GC'ed or manually freed before it ought to?

**Comment by Wimmerer** [comment]
I thought that was most likely. But I'm not sure why GC would be doing this only on one plat. Switching to Refs should fix that also(?).

**Comment by ViralBShah** [comment]
Aren't things like `Numeric` Refs to pointers that have the data? So even if the Ref is safe, the thing it points to could be freed (in theory). I do think it is unlikely, since such things would have surely resulted in many complaints.

**Comment by Wimmerer** [comment]
Who's the expert on differences between Windows and other plats?

**Comment by ViralBShah** [comment]
@vtjnash is one of them.

**Comment by ViralBShah** [comment]
The recent spate of failures have been on CHOLMOD.

**Comment by Keno** [comment]
This is being worked on.

**Comment by ViralBShah** [comment]
The last I spoke with @vtjnash before @keno's comment here, was that it looks like the crash is due to SPQR which seems to be smashing the stack.
