### ISSUE TITLE
Ability to turn on and off scalar indexing for sparse matrices?

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaSparse/SparseArrays.jl#189]
`A[i,j] = ...` is very slow if `A isa SparseMatrixCSC`. In the wild, there's another case like this with CUDA.jl. In that package, it allows for doing `CUDA.allowscalar(false)` so that any `A[i,j]` operation (`getindex` and `setindex!`) causes an error to be thrown. This is helpful for finding unoptimized fallbacks which would otherwise "work" given the AbstractArray interface, but would be detrimental to performance. Without this, finding out which CUDA codes are hitting unwanted fallbacks can only be done by profiling.

It would be nice to have similar functionality available on SparseMatrixCSC. I am not sure I like the idea of having it global though, since then it's global, but if it's not global you need rules for how to carry it forward with broadcast etc. which might be hard to do in general and so the global is the easy option.

**Comment by Wimmerer** [comment]
Is the idea to use this only for testing? I can't imagine it would be a good idea to do this in a package like SciML, disabling it for everything else.

**Comment by ChrisRackauckas** [comment]
Yes, I'd only use it for testing. The main thing would be to ensure we don't hit any fallback that are looping scalar-wise.

**Comment by ViralBShah** [comment]
If you are using with CUDA, you probably want to disable it, right? Packages can opt in to do that, I suppose.

**Comment by ChrisRackauckas** [comment]
Yes, with CUDA its generally the case that you say "if using CUDA, then put `CUDA.allowscalar(false)` in your script because that will catch common performance pitfalls and turn them into errors". The similar fact is true for sparse matrices that if you're doing `A[i,j]` operations all over the place then you'll have bad performance, but there isn't a similar way with SparseMatrixCSC to turn performance pitfalls into errors. 

Of course it can be used incorrectly, the CUDA.jl one could be used incorrectly as well if a package sets it "for the user" and suddenly non-performance sensitive parts of the code are overly cautious, but I think over the years people have found `CUDA.allowscalar(false)` useful enough for testing and scripting safety that it would be nice to have a similar feature for sparse matrices.

**Comment by Wimmerer** [comment]
I definitely prefer the StaticSparseMatrixCSC <: AbstractSparseMatrixCSC route. But it is a little more onerous to implement.

**Comment by ChrisRackauckas** [comment]
What would you do with `A::StaticSparseMatrixCSC .+ B::SparseMatrixCSC`?

**Comment by Wimmerer** [comment]
Would that not just be the union of the patterns?

**Comment by ChrisRackauckas** [comment]
Promote to static?

**Comment by Wimmerer** [comment]
That seems reasonable.

**Comment by wnoise** [comment]
I would have assumed non-static for mixed things like that -- much like a diagonal matrix plus a general matrix gives a general matrix.

**Comment by SobhanMP** [comment]
would it make sense to just disable it? adding any sort of runtime checks seems not ideal, specially for applications that use scalar_indexing a lot.

**Comment by ViralBShah** [comment]
I suppose that would work, but should be done through an API that can disable and re-enable.

**Comment by ChrisRackauckas** [comment]
> specially since it's only for testing. adding any sort of runtime checks seems not ideal, specially for applications that use scalar_indexing a lot.

It already has to assume indirect access with scalar indexing so it already has a few branches that block SIMD and already has other branches that will fail branch prediction. This branch will be the most predictable (almost always true) so it would clearly be the lowest overhead one of the bunch. What would it cost, like 2% performance difference in a code path already deemed too slow to be used in cases where performance is required? I don't understand how that could be the hold up.

**Comment by SobhanMP** [comment]
that's going to make all of the three argument dots of `Symmetric{SparseArraysCSC}` a whooping 2% slower. 

The real question is what would stop you from using a custom `AbstractSparseArraysCSC` that doesn't have scalar indexing? A lot of code have a too narrow type definition and use "illegal" accessors. i.e. x.nzval and such. Seem like two birds with one stone to me.

From a design perspective having global states seem less than ideal.

**Comment by ChrisRackauckas** [comment]
> A lot of code have a too narrow type definition and use "illegal" accessors. i.e. x.nzval and such. Seem like two birds with one stone to me.

? Of course it wouldn't touch `nzval` access because that's supposed to be fast. You want to find out what codes are accidentally doing `A[i,j]` instead of direct `nzval` accesses. 

> that's going to make the three argument dot of Symmetric{SparseArraysCSC} a whooping 2% slower.

If that's falling back to using `A[i,j]`, well then this just identified a performance bug that should get fix. The `dot`, `mul!`, etc. implementations don't use `A[i,j]` for a good reason, and if they do, we should have a way of knowing that they are doing that accidentally so we can make them like 10x faster!

**Comment by SobhanMP** [comment]
> ? Of course it wouldn't touch nzval access because that's supposed to be fast. You want to find out what codes are accidentally doing A[i,j] instead of direct nzval accesses.

you're missing the point, if they didn't have narrow types/did illegal access, it would be pretty easy to cook up a AbstractSparseArraysCSC variant that does what you want.

**Comment by ChrisRackauckas** [comment]
> it would be pretty easy to cook up a AbstractSparseArraysCSC variant that does what you want. and i t would be free of a global state.

No. Counter example: define a `dot` overload only on `SparseMatrixCSC` that avoids an `A[i,j]` indexing. Now your tests for whether a slow path are hit give the wrong answer if it's only relying on `AbstractSparseMatrixCSC` dispatches unless you do some fancy AbstractInterpreter thing to automatically expand all `SparseMatrixCSC` dispatches or something.

**Comment by SobhanMP** [comment]
i see, it's unavoidable if you use structures as you'll need concrete types but it can be still be generic? It still comes back to the fact that having functions that explicitly take SparseMatrixCSCs is a bad idea. (and fairly common)

**Comment by SobhanMP** [comment]
@ChrisRackauckas opinions? should it also block indexings like `A[2, :]`?

**Comment by ChrisRackauckas** [comment]
I would think those are fine. In the GPU case, those are allowed and `allowscalar` still catches the overwhelming majority of bad fallbacks.

**Comment by SobhanMP** [comment]
do note that `A[2, :]` is equivalent to n scalar indexings in this package

**Comment by ChrisRackauckas** [comment]
oh, then that's bad 😅. I guess that would error at the fallback

**Comment by ViralBShah** [comment]
Well it would do what you want - disable the use of scalar indexing. You should not try to extract a row out of a CSC matrix.

**Comment by ChrisRackauckas** [comment]
Agreed.

**Comment by ChrisRackauckas** [comment]
🎉
