### ISSUE TITLE
Non-deterministic CI failures in testset `SparseArrays/spqr`: `rank(qr(S))` and `rank(S)` should be 5, but they are actually 6

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaSparse/SparseArrays.jl#193]
On CI, when testing `x86_64-linux-gnu`, I saw the following test failure:

```
Error in testset SparseArrays/spqr:
Test Failed at /cache/build/default-amdci5-2/julialang/julia-master/julia-8f54c41fa7/share/julia/stdlib/v1.9/SparseArrays/test/spqr.jl:134
  Expression: rank(qr(S)) == 5
   Evaluated: 6 == 5

Error in testset SparseArrays/spqr:
Test Failed at /cache/build/default-amdci5-2/julialang/julia-master/julia-8f54c41fa7/share/julia/stdlib/v1.9/SparseArrays/test/spqr.jl:135
  Expression: rank(S) == 5
   Evaluated: 6 == 5
```

The versioninfo is:

```
Julia Version 1.9.0-DEV.1039
Commit 8f54c41fa7d (2022-07-23 21:24 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 16 × AMD EPYC 7502 32-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.5 (ORCJIT, znver2)
  Threads: 1 on 16 virtual cores
```

The CI log is available here: https://buildkite.com/julialang/julia-master/builds/14229#01822cf2-cf7e-4398-bcb5-876a8f562de7

An rr trace is available. To download the rr trace, go to the CI log and click on the "Artifacts" tab. Please note that rr traces are automatically deleted from Buildkite 180 days after the job.

**Comment by DilumAluthge** [comment]
@ViralBShah Did I open this issue in the right place?

**Comment by SobhanMP** [comment]
seems like the problem isn't likely but a concrete test case can be generated
```julia
using LinearAlgebra, SparseArrays
function f()
    for i in 1:1e10
        A = sprandn(10, 5, 1.0)
        B = sprandn(5, 10, 1.0)
        S = A * B 
        if rank(S) > 5
            
            return i, A, B
        end
    end
end
i, A, B = f()
```

it usually seems to take a few hundred iterations to find one like

```julia
julia> A
10×5 SparseMatrixCSC{Float64, Int64} with 50 stored entries:
 -0.603206   -0.372757    1.45953    -0.432791     2.14448
  2.74288     1.63286    -0.953514    0.131903     0.949612
  0.392631   -0.645688    0.281674    0.564582     0.436059
 -0.591413   -1.13959     0.15177     0.00186669  -0.3145
 -0.824799   -0.0351992  -1.33606    -0.294018    -0.396244
  1.11233    -0.909374    0.666919   -1.04973      0.610208
  0.0617472  -0.205538    0.414579    0.0149338    0.406791
  0.312853    0.148649    1.36359     1.12676      1.03033
  1.36674     0.0631587  -0.0765668  -1.48336     -2.46788
 -0.807339   -0.830126    0.525322   -0.313124    -0.907702
```
and

```
julia> B
5×10 SparseMatrixCSC{Float64, Int64} with 50 stored entries:
 -0.79964   -0.271256    -1.32778     0.00168073  -2.99432   -1.36196    1.27463   -0.211607    -0.194782  -0.0253544
  0.145029   0.00860511   0.548075    0.165        0.965168  -0.742208  -1.87013    1.30313     -1.0952     0.154238
 -0.496839   0.135488    -0.0161235  -0.219981    -0.644988   0.752301  -0.860569  -0.444622     0.988607   0.566755
  0.159561   0.241073     1.0551      0.981269     0.373948  -2.48938   -2.49645    0.300972     0.314867  -1.17151
  1.10145    0.678317    -0.931417   -1.74693      0.769441  -1.36633   -0.435188   0.00953665  -0.788036   1.4781
```
```julia
julia> rank(A * B), rank(Matrix(A) * Matrix(B)), rank(Matrix(A * B))
(6, 5, 5)
```

**Comment by SobhanMP** [comment]
seems like even worse examples exists

(1076, sparse([1, 2, 3, 4, 5, 1, 2, 3, 4, 5], [1, 1, 1, 1, 1, 2, 2, 2, 2, 2], [0.35026062295024907, 0.5588452485964142, -0.40539571399386654, -1.697986700254399, -0.8915606440547018, 0.8831722820688155, -0.411551361030336, 0.5798958499417199, 2.4999503241098755, -0.25417560251343224], 5, 2), sparse([1, 2, 1, 2, 1, 2, 1, 2, 1, 2], [1, 1, 2, 2, 3, 3, 4, 4, 5, 5], [0.14212810366562148, -1.3252128175495834, -0.1411688650408865, 1.3221472882013126, 0.8022920852004064, -0.624303276760448, 0.4794853162193575, 1.427772248638564, -0.8846197860457659, -0.18275209153361457], 2, 5))

**Comment by SobhanMP** [comment]
i think it's not a "bug" per se, it's the just that R matrix's (in the QR) rows are small but not zero which leads to higher ranks than expected. maybe it's not the best method for calculating rank.

**Comment by LilithHafner** [comment]
There are several ways to make the tests stop failing, but these failures do reflect a real bug: `LinearAlgebra.rank(::SparseMatrixCSC)` does not follow the specification described in the docstring: 

> `rank(A::AbstractMatrix; atol::Real=0, rtol::Real=atol>0 ? 0 : n*ϵ)`
>
>  Compute the rank of a matrix by counting how many singular values of `A` have magnitude greater than `max(atol, rtol*σ₁)`...

Rounding error is to be expected, and should be compensated for in the `rank` function by checking if singular values are smaller than a threshold rather than equal to zero. `rank` is documented to accept `atol` and `rtol` with default tolerances high enough to avoid these issues, but SparseArray's `rank` does not implement these tolerances.

Additionally, SparseArrays's `qr` does not always behave identically to LinearAlgebra's `qr`, but I doubt that is the primary issue here.

This is the example I've been working with:
```julia
x = [0.9543 0.4536 1.2126; 0.7052 0.3351 1.1237; 0.6207 0.2952 0.3966];
rank(x) # 2
rank(sparse(x)) # 3
```

**Comment by SobhanMP** [comment]
i somehow feel that cutting the rest of the doc that mentions that that function uses SVD might be the reason that it doesn't follow that API.

**Comment by ViralBShah** [comment]
Does #195 fully address this issue, or do we need to leave it open?

**Comment by LilithHafner** [comment]
It makes the test failure probability less than 1e-10, which is IMO good enough to close the nondeterministic CI failures issue.

However, AFAICT, `rank(::SparseMatrixCSC)` still neither follows the specification from its docstring (which is based on, `atol`, `rtol`, and the magnitude of singular values), nor documents its deviation, nor is as robust by default as `rank(::Matrix)` is.

**Comment by ViralBShah** [comment]
We should note that I'm a separate issue and update the docstring.
