### ISSUE TITLE
CHOLMOD doesnt call `cholmod_l_finish`

### ISSUE THREAD

**Issue by Wimmerer** [JuliaSparse/SparseArrays.jl#205]
In practice I doubt this is a major issue, but it seems odd to me. Is there a reason we don't call `cholmod_l_finish` on the Common objects before Julia quits? @ViralBShah you might know?

**Comment by ViralBShah** [comment]
We should if we can. But like you said, doesn't really matter.

**Comment by ViralBShah** [comment]
With the use of task local storage, do we need to clean this up when a task finishes?

**Comment by SobhanMP** [comment]
Will added a finalizer so it get called now, hence why i closed it. 

https://github.com/JuliaSparse/SparseArrays.jl/blob/0944c410f52051765fb85a51bf3ef4bf6ee46881/src/solvers/cholmod.jl#L155

**Comment by Wimmerer** [comment]
This is good to close yes
