### ISSUE TITLE
`iszero` is very slow

### ISSUE THREAD

**Issue by lgoe-ac** [JuliaSparse/SparseArrays.jl#231]
I suggest implementing a better `iszero` method instead of the default one for AbstractArray by `iszero(v) = count(!iszero, v) == 0`, since this is much faster as it uses the sparseness.

**Comment by eschnett** [comment]
See also https://github.com/JuliaSparse/SparseArrays.jl/pull/227. I assume the problem that that PR solves needs to be addressed more generically for a wider range of reductions, including `iszero`, `isapprox`, ...

**Comment by eschnett** [comment]
Note that `iszero` of a sparse matrix seems fast as of Julia 1.8, but `iszero` of the adjoint or transpose of a sparse matrix is slow.

**Comment by SobhanMP** [comment]
```julia
using Revise, SparseArrays, Test, LinearAlgebra, Cthulhu, Profile, BenchmarkTools
       for a in
           [
               sprand(Int, 100000, 100000, 0.00000001),
               sprand(Int, 100000, 0.0001),
           ]
       
           iszero(a)
           iszero(a.nzval)
           @time iszero(a)
           @time iszero(a.nzval)
       end
[ Info: Precompiling SparseArrays [3f01184e-e22b-5df5-ae63-d93ebab69eaf]
  0.000003 seconds
  0.000011 seconds (1 allocation: 48 bytes)
  0.000037 seconds
  0.000002 seconds (1 allocation: 32 bytes)
```

on main, it's very fast. reduce is optimized for SparseArrays
