### ISSUE TITLE
Julia CI intermittent failure

### ISSUE THREAD

**Issue by timholy** [JuliaSparse/SparseArrays.jl#238]
I see periodic failures of the form
```julia


Error in testset SparseArrays/umfpack:
Test failed at /cache/build/default-amdci5-4/julialang/julia-master/julia-6c45c21f6b/share/julia/stdlib/v1.9/SparseArrays/test/umfpack.jl:373
  Expression: getfield(F1.workspace, nm) == getfield(F2.workspace, nm)
   Evaluated: [6.9368777833479e-310, 6.9368777833511e-310, 
6.9368964637692e-310, 6.93690655368216e-310, 6.9369088769298e-310, 
6.9369186398223e-310, 5.0e-324, NaN, 3.301154e-318, 
6.9369186398219e-310] == [6.9368777833479e-310, 6.9368777833511e-310, 
6.9368964637692e-310, 6.93690655368216e-310, 6.9369088769298e-310, 
6.9369186398223e-310, 5.0e-324, NaN, 3.301154e-318, 
6.9369186398219e-310]
```

The error is presumably triggered because of the presence of the `NaN` entries. While this could be fixed by switching to `isequal`, this seems likely to mask a more serious problem. I doubt this is a problem caused by this library, because
```julia
julia> badm = Ref{Any}()
Base.RefValue{Any}(#undef)

julia> for _ in 1:10^6
           A  = 10*I + sprandn(10, 10, 0.4)
           badm[] = copy(A)
           F1 = lu(A)
           any(isnan, F1.nzval) && error("NaN")
       end
```
never resulted in a NaN.

Examples:
- https://buildkite.com/julialang/julia-master/builds/15058#0182d8f2-6fe4-40e8-828c-b3d87587d68c
- https://buildkite.com/julialang/julia-master/builds/15063#0182d9a2-cb0e-4c97-95ec-f16ab36b312c

While the error may not be caused by code here, we might as well document it here. However, it is very suspicious that it occurs here repeatedly; is one of the underlying C libraries doing something funny?

**Comment by Keno** [comment]
This test was reading uninitialized memory. This is fixed on master.
