### ISSUE TITLE
Add abstract types to factorizations

### ISSUE THREAD

**Issue by Wimmerer** [JuliaSparse/SparseArrays.jl#247]
The current factorizations: UMFPACK, SPQR, and CHOLMOD, are not extensible to other matrix types. This is a pretty deep issue, but there's a relatively simple solution:

I propose that we add `AbstractUMFPACKFactorization`, `AbstractSPQRFactorization` and `AbstractCHOLMODFactorization`. Then we extension can be done by simply defining necessary overloads on a new factorization type like `MyType_UMFPACKFactor <:AbstractUMFPACKFactorization`.

I am doing this in KLU but would like to hear some thought on doing this for the stdlib factors. This simplifies adding new types to LinearSolve as well.

**Comment by SobhanMP** [comment]
i thought the consensus was to not add types in julia 1.9? (looking back at the fixedCSC discussion) also doesn't umfpack only support factorizing csc matrices?

**Comment by Wimmerer** [comment]
Concrete types. Adding an abstract type to an existing concrete type doesn't have the same implications (I think we agreed on AbstractCompressedVector for a similar reason, right?). 

A variety of features including refactoring, printing, and return types are tied directly to SparseMatrixCSC. Resource pinning is also not 1:1 with my packages. 

In the end since this will be only 1.9 it might not be worth the `@static if`s.

**Comment by SobhanMP** [comment]
> A variety of features including refactoring, printing, and return types are tied directly to SparseMatrixCSC. Resource pinning is also not 1:1 with my packages.

can you elaborate?

**Comment by Wimmerer** [comment]
> refactoring

This one is mostly okay, except we don't really know what the parent matrix type of the factorization is. We know it's in CSC format broadly, but it could be 1 or 0 based, and the methods to get the pointers/indexes are not necessarily easy to extend to something that lives in C (or C++/MLIR sparse or whatever) for instance. Allowing the refactor methods to be extensible fixes this by extending at a higher level where necessary.

> Printing && return types

This will always be SparseMatrixCSC, since, again, we have no information about the parent array of the factorization. Recovering the original type from a SparseMatrixCSC can be expensive.

> Pinning resources

The UMFPACK factorization, for instance, keeps Vectors it has decremented. This isn't ideal for the implementations I'm working on both in Julia and C.

It's easy enough for me to copy the code in its entirety, and since I have to do that for LTS it's what I'll probably do anyway.
