### ISSUE TITLE
Support `ldiv!` SuiteSparse.CHOLMOD.Factor

### ISSUE THREAD

**Issue by amontoison** [JuliaSparse/SparseArrays.jl#275]
I through that it was not supported in `SuiteSparse` but it's not the case (https://github.com/DrTimothyAldenDavis/SuiteSparse/issues/136).
We could do something similar to https://github.com/SobhanMP/SuiteSparse.jl/commit/7093e4ac176787983b56f8f157c294cae28ca034 and add the additional two vectors `Y` and `E` in the Julia structure.

[CHOLMOD_UserGuide.pdf](https://github.com/JuliaSparse/SparseArrays.jl/files/9793362/CHOLMOD_UserGuide.pdf) <- pages 119-120.

**Comment by Wimmerer** [comment]
I'll try to get this added for 1.9. If you need it in previous versions I'm entertaining a CHOLMOD.jl separate from SparseArrays.jl

**Comment by amontoison** [comment]
Thanks @Wimmerer! No, I don't need it for previous versions. If you can add it for Julia 1.9 or 1.10, it's perfect.

**Comment by t-bltg** [comment]
Is this being worked on ?

**Comment by stevengj** [comment]
See also #319.
