### ISSUE TITLE
-0.0, storing zeros other than zero(eltype(v))

### ISSUE THREAD

**Issue by LilithHafner** [JuliaSparse/SparseArrays.jl#294]
For almost any value and assignable expression in Julia, this holds:
```julia
expr = value
@assert expr === value
```
I wish this held, too:
```julia
v = spzeros(1)
value = -0.0
v[1] = value
@assert v[1] === value
```

**Comment by chriselrod** [comment]
No.
```julia
julia> v = zeros(1);

julia> value = 0;

julia> v[1] = value;

julia> @assert v[1] === value
ERROR: AssertionError: v[1] === value
Stacktrace:
 [1] top-level scope
   @ REPL[18]:1
```

**Comment by SobhanMP** [comment]
1: you're forcing the type here tho, that's not part of @LilithHafner's point
2: not all zeros are equal, i personally learned it the hard way https://github.com/JuliaDiff/ForwardDiff.jl/issues/542 this way we only remove zeros we are sure we can restore.
