### ISSUE TITLE
libsuitesparseconfig.so.7: undefined symbol: SuiteSparse_config

### ISSUE THREAD

**Issue by Heptazhou** [JuliaSparse/SparseArrays.jl#332]
Hi,

with julia v1.8.5 and suitesparse v7.0.0 (on Archlinux),
everytime julia runs, it gives
```jl
% julia
┌ Error: Error during initialization of module CHOLMOD
│   exception =
│    could not load symbol "SuiteSparse_config":
│    /usr/lib/libsuitesparseconfig.so.7: undefined symbol: SuiteSparse_config
└ @ SuiteSparse.CHOLMOD /build/julia/src/julia-1.8.5/usr/share/julia/stdlib/v1.8/SuiteSparse/src/cholmod.jl:230
```
which (I believe) is raised by <https://github.com/JuliaSparse/SparseArrays.jl/blob/c7ad0b94dca511ef7566b5bca9d612fe1a3473ee/src/solvers/cholmod.jl#L233-L244>

and I think that the reason is just suitesparse v7 removed the visibility of `SuiteSparse_config` (<https://github.com/DrTimothyAldenDavis/SuiteSparse/releases/tag/v7.0.0>).

I wonder will there be a fix for this?

**Comment by ViralBShah** [comment]
@DrTimothyAldenDavis What should we do to address this?

**Comment by DrTimothyAldenDavis** [comment]
It's a quick fix. I have accessor functions that give access to those components of the struct. For both reading and writing. 

The visibility of this struct was causing problems with my port to Windows so I had to make the struct private.

**Comment by DrTimothyAldenDavis** [comment]
So instead of doing

SuiteSparse_config.malloc = mymalloc 

You just need to call

SuiteSparse_config_malloc_func_set (mymalloc) ;

And likewise for the other functions. 

This change is why I had to bump the so of SuiteSparse from 6.x to 7.x.

**Comment by ViralBShah** [comment]
Ah ok. So we no longer then need to have this global config as well, and can just replace all those calls as you discussed.

We are still shipping 6.x - but some users who are not using the official binaries are ahead, and are seeing this, which gives us a chance to fix it in preparation for 7.x. Thank you.

**Comment by DrTimothyAldenDavis** [comment]
Yes, that sounds like a good plan.  Let me know if you need anything to make the change.  It should be straight-forward.

**Comment by fxcoudert** [comment]
@DrTimothyAldenDavis I have proposed a PR at https://github.com/JuliaSparse/SparseArrays.jl/pull/353

The change is in suitesparse >= 7, which corresponds to cholmod version >= 4.0.3, did I get that right?

**Comment by ahazra** [comment]
Setting alias julia='LD_LIBRARY_PATH=" " julia' seems to have solved the problem. But how can I set this configuration in VSCODE? It would be great if anyone can inform me.
