### ISSUE TITLE
Move to actually using JLLs

### ISSUE THREAD

**Issue by staticfloat** [JuliaSparse/SparseArrays.jl#349]
I believe we should be able to actually use the JLLs that ship with Julia as hinted at in this comment:

https://github.com/JuliaSparse/SparseArrays.jl/blob/38604c3b9f80059f108b196853d2ab9f9956c986/src/solvers/LibSuiteSparse.jl#L3-L6

This should standardize the library SONAME used by the main Julia distribution.

**Comment by ViralBShah** [comment]
What exactly do we need to do?

**Comment by vtjnash** [comment]
It looks like we still need to delete the vendored copies of the JLL files, if we want to claim to have actually be using the JLLs correctly now.
https://github.com/JuliaSparse/SparseArrays.jl/blob/main/src/solvers/LibSuiteSparse.jl and https://github.com/JuliaSparse/SparseArrays.jl/blob/main/src/solvers/lib

**Comment by vtjnash** [comment]
In particular, these values are wrong
https://github.com/JuliaSparse/SparseArrays.jl/blob/5fc57713156beea140a0ae7d1ceacbc7d3320c07/src/solvers/lib/aarch64-apple-darwin20.jl#L2400-L2404
since there was no "compat" entry added in #378.

**Comment by ViralBShah** [comment]
That is not the real issue. We are stuck in a bad place with a SuiteSparse upgrade.

**Comment by vtjnash** [comment]
It is at least missing a compat entry for the JLL, since it is enforcing a CHOLMOD_*_VERSION value there, but not declaring that for the JLL dependency.

**Comment by ViralBShah** [comment]
> It looks like we still need to delete the vendored copies of the JLL files, if we want to claim to have actually be using the JLLs correctly now. https://github.com/JuliaSparse/SparseArrays.jl/blob/main/src/solvers/LibSuiteSparse.jl and https://github.com/JuliaSparse/SparseArrays.jl/blob/main/src/solvers/lib

I don't really understand what this means. These are autogenerated clang wrappers around suitesparse solvers that live in SparseArrays.jl. They used to live in SuiteSparse.jl, but I don't remember why we moved them to SparseArrays.jl.

**Comment by vtjnash** [comment]
Ah, okay, I thought that was content from the JLL since it seemed to re-declare the version information from the JLL. There should be a compat entry in this package, which matches the CHOLMOD_*_VERSION value, based on the version of SuiteSparse_jll overall.

**Comment by ViralBShah** [comment]
It doesn't make sense for this package to have a compat entry that is the cholmod version. If anything, this package should have a compat entry that is the julia version.

**Comment by vtjnash** [comment]
It seems like currently (due to https://github.com/JuliaSparse/SparseArrays.jl/commit/691287e7365d11b9ac3731e09d94a4d2be13eebf) this package is currently incompatible with all existing versions of SuiteSparse_jll, so that may also need to be reverted, then relanded with correct compat bounds
