### ISSUE TITLE
`sum` init arg ignored for 1xN sparse arrays

### ISSUE THREAD

**Issue by btmit** [JuliaSparse/SparseArrays.jl#365]
```julia
julia> a = sparse([1], [1], [1.], 1, 2)
1×2 SparseMatrixCSC{Float64, Int64} with 1 stored entry:
 1.0   ⋅ 

julia> sum(a; dims=2, init=1.0)
1×1 Matrix{Float64}:
 1.0
```

This returns `1.0` not `2.0` - aka the init value is ignored. 

Note that changing to a NxM matrix gives the right answer:

```julia
julia> b = sparse([1], [1], [1.], 2, 2)
2×2 SparseMatrixCSC{Float64, Int64} with 1 stored entry:
 1.0   ⋅ 
  ⋅    ⋅ 

julia> sum(b; dims=2, init=1.0)
2×1 Matrix{Float64}:
 2.0
 1.0
```

I'm seeing this in 1.8.5 and 1.9-rc1.

**Comment by fredrikekre** [comment]
The docstring for `sum`:

> The value returned for empty itr can be specified by init. It must be the additive identity (i.e. zero) as it is unspecified whether init is used for non-empty collections.
