### ISSUE TITLE
Updates necessary for SuiteSparse 7

### ISSUE THREAD

**Issue by ViralBShah** [JuliaSparse/SparseArrays.jl#374]
In [SuiteSparse 6](https://github.com/DrTimothyAldenDavis/SuiteSparse/releases/tag/v6.0.0), `SuiteSparse_long` was deprecated, and you have to explicitly pick `int32_t` or `int64_t`. This makes things simpler, since we have a bit of complex logic in how we dispatch to `cholmod_l` routines.

We'll need to update the interfaces in line with this change for SuiteSparse 7 (we skipped 6). The `vs/suitesparse7` branch in [PR 48977](https://github.com/JuliaLang/julia/pull/48977) on `julialang/julia` is prepared for this and needs a new version of SparseArrays.jl that updates the interfaces. It passes on 64-bit platforms, and fails on 32-bit currently.

cc @fxcoudert @Wimmerer @Gnimuc

**Comment by PallHaraldsson** [comment]
Does it make a lot of sense to support SuiteSparse on 32-bit platforms, if it's a problem? We (at least I) want to get rid of it, for GPL-free Julia, by default, and could start that way for 32-bit Julia only? If people really need it they could use older Julia...

[I mean drop it, tough not necessarily SparseArrays too. For either or both it would be a precedence though...]

**Comment by Wimmerer** [comment]
We definitely cannot drop SuiteSparse for 32-bit. This would be a breaking change.

Tim is very receptive to stuff like this, and his solution sounds perfectly fine. Indeed it sounds like we might be able to get away with converting to 64-bit indices for certain arguments in the meantime.

**Comment by ViralBShah** [comment]
Will be accomplished in https://github.com/JuliaLang/julia/pull/48977
