### ISSUE TITLE
Solving a system of linear equations  `A\b` uses up more memory when `A` is sparse then when `A` is dense

### ISSUE THREAD

**Issue by lampretl** [JuliaSparse/SparseArrays.jl#412]
In Julia 1.9.1 I ran the code below with the built-in library SparseArrays.jl (that now contains SuiteSparse.jl):
```
using SparseArrays
n, s = 5*10^4, 20;   A, b = sprand(n,n,s/n), sprand(n,s/n);

@time (x = Array(A) \ Array(b));   println(maximum(abs.(A*x-b)))  # solving with a dense matrix
# 696.465488 seconds (10 allocations: 37.254 GiB, 0.00% gc time)
# 9.847483939395829e-12

@time (x = A \ Array(b));   println(maximum(abs.(A*x-b)))  
# 613.900805 seconds (87 allocations: 50.173 GiB, 0.00% gc time)
# 1.601508370363547e-10
```
As we can see, the timing is comparable, but the sparse version **requires more memory** than if we convert `A` to a dense matrix and compute with that, making the method not particularly useful. The whole point of sparse arrays is to save up on memory by not storing the abundant zeros.

I've mentioned this behaviour in https://github.com/SciML/LinearSolve.jl/issues/340 and opened a similar issue in https://github.com/SciML/LinearSolve.jl/issues/342

**Comment by ViralBShah** [comment]
See discussion in the linked issue.
