### ISSUE TITLE
SparseMatrixCSC format cannot handle efficiently very large matrices

### ISSUE THREAD

**Issue by laurentbartholdi** [JuliaSparse/SparseArrays.jl#424]
This is not a bug, but rather a feature request. The current implementation of SparseMatrixCSC is
```
struct SparseMatrixCSC{Tv,Ti<:Integer} <: AbstractSparseMatrixCSC{Tv,Ti}
    m::Int                  # Number of rows
    n::Int                  # Number of columns
    colptr::Vector{Ti}      # Column i is in colptr[i]:(colptr[i+1]-1)
    rowval::Vector{Ti}      # Row indices of stored values
    nzval::Vector{Tv}       # Stored values, typically nonzeros
```
and I believe the array `colptr` should be of type `Vector{Int}`, not `Vector{Ti}`. Indeed its size is very small compared to the next two arrays; it often happens that one has matrices with more than $2^{32}$ nonzeros, but very seldom do they have more than $2^{32}$ rows or columns. Thus the memory footprint of a sparse matrix (say with size 1Mx1M and density 0.01) can be almost halved by having it of type `SparseMatrixCSC{Float32,Int32}`, with $10^{10}$ entries in `rowval` and `nzval`.

**Comment by SobhanMP** [comment]
What you say makes sense but would require breaking so much code.

 alternatively, you can define your own CSC type, and the functions in this package should work on it.

**Comment by ojwoodford** [comment]
Halving memory requirements is not a scalable solution, unfortunately. Once your problems are twice as big, you run into the same problem.

**Comment by Wimmerer** [comment]
This is done pretty commonly, especially in distributed settings. But we can't support it here.
