### ISSUE TITLE
Unable to sum `::SparseVector{Num,Int}`s

### ISSUE THREAD

**Issue by vtjnash** [JuliaSparse/SparseArrays.jl#435]
From https://discourse.julialang.org/t/is-there-a-defined-minimal-interface-for-a-type-to-work-with-sparsearrays/69602/2

```julia
using Symbolics, SparseArrays

@variables a
v = sparsevec([1], [a])
v+v #  throws 
```

_Originally posted at https://github.com/JuliaLang/julia/issues/42730 by @abraunst_

**Comment by jishnub** [comment]
Seems fixed on main
```julia
julia> v+v
1-element SparseVector{Num, Int64} with 1 stored entry:
  [1]  =  2a
```
