### ISSUE TITLE
JLL-style LibSuiteSparse headers are incompatible with new platforms 

### ISSUE THREAD

**Issue by maleadt** [JuliaSparse/SparseArrays.jl#445]
During bringup of Julia on a non BB-supported platform, i.e., compiling Julia with `USE_BINARYBUILDER := 0`, I ran into the fact that SparseArrays.jl's LibSuiteSparse.jl behaves pretty much like a JLL, in that it only supports a fixed set of platforms: https://github.com/JuliaSparse/SparseArrays.jl/blob/ac5c8ed5e87af863d62892693f683543b122bb76/src/solvers/LibSuiteSparse.jl#L33-L39

This seems needlessly complicated, especially because the headers are in fact identical:

```
❯ md5sum *
7de9f4584578f167cc12bf5000883b8c  aarch64-apple-darwin20.jl
7de9f4584578f167cc12bf5000883b8c  aarch64-linux-gnu.jl
7de9f4584578f167cc12bf5000883b8c  aarch64-linux-musl.jl
7de9f4584578f167cc12bf5000883b8c  armv7l-linux-gnueabihf.jl
7de9f4584578f167cc12bf5000883b8c  armv7l-linux-musleabihf.jl
7de9f4584578f167cc12bf5000883b8c  i686-linux-gnu.jl
7de9f4584578f167cc12bf5000883b8c  i686-linux-musl.jl
7de9f4584578f167cc12bf5000883b8c  i686-w64-mingw32.jl
7de9f4584578f167cc12bf5000883b8c  powerpc64le-linux-gnu.jl
7de9f4584578f167cc12bf5000883b8c  x86_64-apple-darwin14.jl
7de9f4584578f167cc12bf5000883b8c  x86_64-linux-gnu.jl
7de9f4584578f167cc12bf5000883b8c  x86_64-linux-musl.jl
7de9f4584578f167cc12bf5000883b8c  x86_64-unknown-freebsd.jl
7de9f4584578f167cc12bf5000883b8c  x86_64-w64-mingw32.jl
```

As we still support building Julia without BB support (and we probably always will), can we get rid of this complexity and move to a single `libsuitesparse.jl` header? Or am I missing anything?

**Comment by ViralBShah** [comment]
This is just what the clang.jl script generates, which was written a while ago. We can make it generate something simpler.

**Comment by maleadt** [comment]
I see. I'll create a PR to simplify it then.

**Comment by ViralBShah** [comment]
It's being done here: https://github.com/JuliaSparse/SparseArrays.jl/blob/ac5c8ed5e87af863d62892693f683543b122bb76/gen/generator.jl#L27
