### ISSUE TITLE
Wrapper generator needs updating to pick SuiteSparse headers from new location

### ISSUE THREAD

**Issue by ViralBShah** [JuliaSparse/SparseArrays.jl#482]
As discussed in https://github.com/JuliaLang/julia/pull/52577#issuecomment-1874352276, the wrapper generator script needs updating to pick up the SuiteSparse headers from the new location (in stdlib) in the Julia distribtution.

@rayegun You may already have this in a PR - just making sure I note this here so it is not lost.

```
➜  gen git:(main) julia --project generator.jl
ERROR: LoadError: AssertionError: isfile(cholmod_h)
Stacktrace:
 [1] top-level scope
   @ ~/repos/SparseArrays.jl/gen/generator.jl:15
in expression starting at /Users/viral/repos/SparseArrays.jl/gen/generator.jl:15
```

**Comment by giordano** [comment]
I have a fix in a branch, will push it to #478
