### ISSUE TITLE
Single precision support in CHOLMOD

### ISSUE THREAD

**Issue by ViralBShah** [JuliaSparse/SparseArrays.jl#483]
SuiteSparse 7.4 has single precision support for CHOLMOD: https://github.com/DrTimothyAldenDavis/SuiteSparse/issues/447.

**Comment by ViralBShah** [comment]
@rayegun Do you have a rough idea of how we may need to go about doing this?

**Comment by rayegun** [comment]
Yep, should be relatively easy

**Comment by ViralBShah** [comment]
Fixed in #487
