### ISSUE TITLE
Conversion from SparseMatrixCSC to Matrix uses the same `eltype`.

### ISSUE THREAD

**Issue by blegat** [JuliaSparse/SparseArrays.jl#49]
When converting a SparseMatrixCSC to a Matrix, the current implementation assumes that it can store the result in a matrix of the same `eltype`

https://github.com/JuliaLang/julia/blob/989de7903e492aa25f5a888c19b4b8e8a3f9f1f0/stdlib/SparseArrays/src/sparsematrix.jl#L404

However, this does not work of `zero` of the `eltype` returns an element of a different type.

MCWE:
```julia
struct A end
Base.zero(::Type{A}) = 0
using SparseArrays
S = sparse([1, 2], [1, 2], [A(), A()])
Matrix(S)
```
output:
```
ERROR: LoadError: MethodError: Cannot `convert` an object of type Int64 to an object of type A
Closest candidates are:
  convert(::Type{T}, ::T) where T at essentials.jl:123
Stacktrace:
 [1] fill!(::Array{A,2}, ::Int64) at ./array.jl:220
 [2] zeros at ./array.jl:403 [inlined]
 [3] zeros at ./array.jl:400 [inlined]
 [4] Array{T,2} where T(::SparseMatrixCSC{A,Int64}) at /home/blegat/git/julia/usr/share/julia/stdlib/v0.7/SparseArrays/src/sparsematrix.jl:404
...
```
The error is due to the call `zero(A, 2, 2)`.

This example is a bit artificial but the problem [also occurs in JuMP](https://github.com/JuliaOpt/JuMP.jl/issues/1275) with sparse matrices of `VariableRef` for which the zero type is `AffExpr`.

**Comment by SobhanMP** [comment]
from the doc of `zero`
> Get the additive identity element for the type of x
this is just wrong.
