### ISSUE TITLE
Memory Mapped SparseArrays

### ISSUE THREAD

**Issue by orenbenkiki** [JuliaSparse/SparseArrays.jl#513]
I'm trying to create a sparse vector and matrix where the arrays are memory-mapped. This, alas, means that the type of `nzind`, `colptr`, `rowval`, `nzval` is not a `Vector` but a `ReinterpretArray`. I also need to create sparse vectors or matrices using vectors provided by Python code (that is, `PyArray`).

Due to Julia's type system restrictions, even though all these arrays are actually dense (contiguous in memory), there's no way to express this in the type system.

The `SparseArrays` code insists that the type of these data members be exactly `Vector`, nothing else.

Is there any reason not to change the definition to allow for any `AbstractVector` type for these data members?

If there's a concern that people will try to use strange array types, it is sufficient to `@assert strides(vector) == (1,)` to ensure that the array is contiguous (that is, *effectively* a regular `Vector`).

I could try and create a PR if that makes sense?

**Comment by SobhanMP** [comment]
> Due to Julia's type system restrictions, even though all these arrays are actually dense (contiguous in memory), there's no way to express this in the type system.

As far as I know, you need to define your implementation of `AbstractSparseMatrixCSC` that uses other types; there is no requirement that the results are contiguous in memory. 

If you have a valid implementation of `AbstractSparseMatrixCSC` (with all the required functions), and something does not work, please open another bug report.

Also, you can't update `LinearAlgebra`; you may have to use the nightly Julia. (I could be wrong)

**Comment by rayegun** [comment]
You can make changes to LinearAlgebra but you need to modify the Project.toml for that stdlib to change the uuid if I recall correctly.
