### ISSUE TITLE
Attempting to run sparse `qr` produces StackOverflow when run on a sparse matrix of `ForwardDiff.Dual`.

### ISSUE THREAD

**Issue by lukas-weber** [JuliaSparse/SparseArrays.jl#515]
Hi, I’m aware that the QR decomposition wrapped by SparseArrays.jl only works on `Float64` and `ComplexF64`. However, when trying it anyway, some types with `float(T) == T` such as `ForwardDiff.Dual` can cause an endless recursion.

### Example
```julia
using SparseArrays
A = ForwardDiff.Dual.(sprand(10, 10, 0.1))
qr(A)
```

```
ERROR: StackOverflowError:
Stacktrace:
 [1] SparseMatrixCSC{Dual{Nothing, Float64, 0}, Int64}(m::Int64, n::Int64, colptr::Vector{Int64}, rowval::Vector{Int64}, nzval::Vector{Dual{Nothing, Float64, 0}})
   @ SparseArrays ~/.julia/juliaup/julia-1.10.1+0.x64.linux.gnu/share/julia/stdlib/v1.10/SparseArrays/src/sparsematrix.jl:26
 [2] SparseMatrixCSC(m::Int64, n::Int64, colptr::Vector{Int64}, rowval::Vector{Int64}, nzval::Vector{Dual{Nothing, Float64, 0}})
   @ SparseArrays ~/.julia/juliaup/julia-1.10.1+0.x64.linux.gnu/share/julia/stdlib/v1.10/SparseArrays/src/sparsematrix.jl:44
 [3] float
   @ ~/.julia/juliaup/julia-1.10.1+0.x64.linux.gnu/share/julia/stdlib/v1.10/SparseArrays/src/sparsematrix.jl:983 [inlined]
 [4] qr(A::SparseMatrixCSC{Dual{Nothing, Float64, 0}, Int64}; tol::Dual{Nothing, Float64, 0}) (repeats 39991 times)
   @ SparseArrays.SPQR ~/.julia/juliaup/julia-1.10.1+0.x64.linux.gnu/share/julia/stdlib/v1.10/SparseArrays/src/solvers/spqr.jl:227
```

**Comment by SobhanMP** [comment]
What would be a good solution? I think it's easy to check if `typeof(float(A)) === typeof(A)`, but what about types where float(A) has a cyclic behavior? For instance, imagine 3 matrices A, B, and C where `float(A) == B,` `float(B) == C,` and `float(C) == A.` Can such a type exist in Julia?

**Comment by lukas-weber** [comment]
I think cycles can exist per-se.

How about checking `isprimitivetype(real(float(A)))`? This works only if the type directly decays to one of those, but for types that need multiple iterations of `float` to decay (if they exist), it could be the responsibility of the user to do the conversion.

**Comment by SobhanMP** [comment]
@rayegun the QR factorization only works on Float64, right? Can we directly cast to Float64?

**Comment by rayegun** [comment]
And ComplexF64

**Comment by SobhanMP** [comment]
But can we just cast it directly to F64/CF64? (i.e. replace float(A) with Float64.(A))?

**Comment by rayegun** [comment]
Yes
