### ISSUE TITLE
Broken dtype detection in CHOLMOD in 1.11

### ISSUE THREAD

**Issue by pawel-tarasiuk-quantumz** [JuliaSparse/SparseArrays.jl#585]
Computing `qr` factorization on `SparseMatrixCSC{Float32}` causes an error with Julia 1.11:

```Julia
using SparseArrays, LinearAlgebra
A = sprandn(Float32, 10, 10, 0.5)
qr(Float64.(A))  # works proprely
qr(A)   # !!!
```

Message:
```
ERROR: SparseArrays.CHOLMOD.CHOLMODException("dtype=0 not supported")
Stacktrace:
 [1] SparseArrays.CHOLMOD.Dense{Float32}(ptr::Ptr{SparseArrays.LibSuiteSparse.cholmod_dense_struct})
   @ SparseArrays.CHOLMOD ~/.julia/juliaup/julia-1.11.1+0.x64.linux.gnu/share/julia/stdlib/v1.11/SparseArrays/src/solvers/cholmod.jl:276
 [2] qr(A::SparseMatrixCSC{Float32, Int64}; tol::Float32, ordering::Int32)
   @ SparseArrays.SPQR ~/.julia/juliaup/julia-1.11.1+0.x64.linux.gnu/share/julia/stdlib/v1.11/SparseArrays/src/solvers/spqr.jl:209
 [3] qr(A::SparseMatrixCSC{Float32, Int64})
   @ SparseArrays.SPQR ~/.julia/juliaup/julia-1.11.1+0.x64.linux.gnu/share/julia/stdlib/v1.11/SparseArrays/src/solvers/spqr.jl:195
 [4] top-level scope
   @ REPL[4]:1
```

Tested on clean Julia 1.11 setup with juliaup on Ubuntu 22.04, x86_64. Eqivalent setup with Julia 1.10 works for either element type.

It would seem that https://github.com/JuliaSparse/SparseArrays.jl/blob/1b4933ccc7b1f97427ff88bd7ba58950021f2c60/src/solvers/spqr.jl#L200 does not indicate the proper `dtype`, as `unsafe_load(HTau[]).dtype` is `0` when run for either type. This is incidentally equal to `CHOLMOD_DOUBLE`, which allows the computation for `Float64`.

**Comment by pawel-tarasiuk-quantumz** [comment]
Since `dtype` mismatch is possible, it might be worth to support varied results with no assumptions, as proposed in https://github.com/JuliaSparse/SparseArrays.jl/pull/586.

**Comment by ViralBShah** [comment]
Thanks - merged. I think this started happening because CHOLMOD recently added Float32 support, which we enabled - but we still needed to extend it to QR - which you have now.
