### ISSUE TITLE
Double transposition does not sort sparse matrix entries within columns 

### ISSUE THREAD

**Issue by goulart-paul** [JuliaSparse/SparseArrays.jl#82]
The documentation [here](https://docs.julialang.org/en/v1/stdlib/SparseArrays/) says that when constructing a `SparseMatrixCSC` from data: "If your SparseMatrixCSC object contains unsorted row indices, one quick way to sort them is by doing a double transpose."   This appears not to work.   I think (but am not sure) that it used to work using the now deprecated `.'` operator.

It is possible to force a fix to the row ordering by doing a double transposition with an elementwise multiplication by 1., i.e. something like `A = (A'.*1.)'.*1.`, but that does not seem ideal.

Display of a matrix with unsorted row entries is also broken in v1.7, although displaying post conversion to a dense `Matrix` gives the correct result.   In v1.5 the display function would just list the matrix entries, so was correct even if they were shown in the unconventional ordering.

Example :
```julia
#Standard CSC format
colptr = [1,4,6,8]
rowval = [1,2,3,1,3,2,3]
nzval  = [1., 2., 3., 4., 5., 6., 7.]
m      = 3
n      = 3

A1 = SparseMatrixCSC(m,n,colptr,rowval,nzval)

#Same matrix, but with the entries in the first column disordered
colptr = [1,4,6,8]
rowval = [3,1,2,1,3,2,3]
nzval  = [3., 1., 2., 4., 5., 6., 7.]
m      = 3
n      = 3

A2 = SparseMatrixCSC(m,n,colptr,rowval,nzval)

#display is broken 
display(A1)  #likes correct 
display(A2) #first column is incorrect 
display(Matrix(A2)) #now looks correct

#are they they same?
A1 == A2                 #returns false
Matrix(A1) == Matrix(A2) #returns true

#double transpose
A2 = (A2')'

#are they they same now?
A1 == A2                 #returns false, col 1 still disordered
Matrix(A1) == Matrix(A2) #returns true

#double transpose with multiplies
A2 = (A2'.*1.)'.*1.

#are they they same now?
A1 == A2                 #returns true
Matrix(A1) == Matrix(A2) #returns true
```

**Comment by KristofferC** [comment]
Transpose is now lazy so you probably need to use `copy` like `copy(copy(A2')')`.

**Comment by ViralBShah** [comment]
@goulart-paul If you can verify that, would you be able to submit a PR to that effect to the documentation?

**Comment by goulart-paul** [comment]
I am happy to do that, but I think the double copy seems unnecessarily slow.   Note:

```julia 
n = 20000
A = sprandn(n,n,0.05)

#double copy method
f1(A) = copy(copy(A')') 

#direct sort within of columns
f2(A,n) = SparseArrays.permute_rows!(A,collect(1:n))
```
The first method gives this result:
```
@benchmark f1(A)
BenchmarkTools.Trial: 4 samples with 1 evaluation.
 Range (min … max):  1.196 s …   1.397 s  ┊ GC (min … max): 1.29% … 6.78%
 Time  (median):     1.312 s              ┊ GC (median):    2.31%
 Time  (mean ± σ):   1.305 s ± 83.611 ms  ┊ GC (mean ± σ):  2.99% ± 2.95%
Memory estimate: 610.59 MiB, allocs estimate: 19.
```

While the second gives this result:
```
@benchmark f2(A,n)
BenchmarkTools.Trial: 24 samples with 1 evaluation.
 Range (min … max):  201.115 ms … 219.781 ms  ┊ GC (min … max): 0.00% … 0.00%
 Time  (median):     208.341 ms               ┊ GC (median):    0.00%
 Time  (mean ± σ):   208.524 ms ±   3.659 ms  ┊ GC (mean ± σ):  0.00% ± 0.00%
Memory estimate: 625.23 KiB, allocs estimate: 9.
```
The second one relies on an internal function not presently exported though.   I'm happy to test that, write a wrapper and update the docs if that seems reasonable.   I didn't test it extensively because I would need to think of a way to generate a CSC matrix in non-standard format in the first place.

It would also need a catchy name.
