### ISSUE TITLE
SuiteSparse wastes memory: duplication of sparse matrix storage

### ISSUE THREAD

**Issue by PetrKryslUCSD** [JuliaSparse/SparseArrays.jl#88]
The issue is https://discourse.julialang.org/t/problem-with-suitesparse-memory-duplication/78977

Due to the duplication of the sparse matrix storage when it is converted to `Sparse`, use of the library leads to wasteful memory management. 

I think we need a Julia-only library for this purpose.

**Comment by Wimmerer** [comment]
I'm actively working on an exact port of KLU to Julia. I suspect we can do somewhat better on some solvers like UMFPACK and avoid a copy or two. But I'll have to look further into CHOLMOD and SPQR for that.

**Comment by Wimmerer** [comment]
Part of the reason is we need to decrement the sparse array vectors when using SuiteSparse to be zero based. I'm not sure we can really get around that issue easily.

**Comment by ViralBShah** [comment]
Do you have some examples where this causes a memory issue? Usually, the factorizations of sparse matrices have fill in, which gets worse with larger matrices - and so this extra copy is not really a problem.

I suppose you can decrement! in place yourself, call the solver API directly and then increment! again afterwards - but be sure it is worthwhile to do that.

Writing supernodal or multifrontal sparse solvers is a lot of effort - instead just doing what I suggested above is trivial, if necessary. While it is likely a pure Julia left looking solver may come up soon (and is valuable in many situations), it only makes sense to use if your problems have very little structure.

**Comment by ViralBShah** [comment]
Specifically, we can't do much in the current codebase. Hence closing.
