### ISSUE TITLE
Support Sparse arrays with static sparsity pattern

### ISSUE THREAD

**Issue by SobhanMP** [JuliaSparse/SparseArrays.jl#89]
The title is pretty self explanatory but i have a use case where i have 10^6 arrays with the same sparsity pattern (all the field except nzval are the same). 

on one hand i'm replicating the sparsity pattern many times and on one hand i want some sort of error when operations try to change the sparsity pattern.

Would this be easy to add? does it even fit the scope of the package?

**Comment by SobhanMP** [comment]
yes these are all nice but the moment someone writes on it by accident it starts breaking everything else i.e. if there are multiple arrays with the same rowval/colptr but one of them adds a new cell (by accident) it will cause weird bugs

**Comment by stevengj** [comment]
So you want to support a shared `colptr` and `rowval` but with [ReadOnlyArrays](https://github.com/bkamins/ReadOnlyArrays.jl) or similar?

Right now we only support `Vector` for the indices, but I suppose we could broaden the type signature.

**Comment by SobhanMP** [comment]
yes! exactly!
(i had not seen ReadOnlyArrays)

**Comment by ViralBShah** [comment]
I would suggest building this capability in a separate package, since SparseArrays ships as a Julia stdlib, and we don't want to grow its surface too much. We can restructure the code in here as necessary to support extensions in external packages.

**Comment by Wimmerer** [comment]
Specifically at some point I think it would be nice to separate the abstract types and a few functions into a separate package to enable better extension.

This can be done more easily after 1.9.

**Comment by SobhanMP** [comment]
but unless the type of SparseMatrixCSC becomes more generic, it won't be possible to use solve on them, no?

**Comment by Wimmerer** [comment]
Can you elaborate on that question @SobhanMP?

**Comment by ViralBShah** [comment]
We want to support using the solver infrastructure for other sparse matrices, rather than making SparseMatrixCSC too special. Basically, we want our sparse stuff to be extensible and more abstract.

**Comment by Wimmerer** [comment]
Yes, the solver packages themselves should be less dependent on SparseMatrixCSC, rather than extending SparseMatrixCSC too much. I'm experimenting with this a little bit in KLU.jl. It's not too difficult, the solvers just need 3 vectors after all, the problems are making it elegant and extensible.

**Comment by SobhanMP** [comment]
@Wimmerer my point that other abstract matrix CSCs can't use the solvers even though they are well supported. What i had in mind was encoding the type of the 3 vectors in SparseMatrixCSC but an abstract interface might just work. Making things more abstract does seem like the more elegant of the two possibilities.

**Comment by Wimmerer** [comment]
We need to have it work better using the accessors `getcolptr` etc. It's still hard for me to support that in SuiteSparseGraphBLAS.jl, but anything Julia native should be able to do that just fine, and it means we can support any by-col AbstractSparseMatrix.

**Comment by SobhanMP** [comment]
guess it's time to bring back that this patch https://github.com/juliaSparse/SparseArrays.jl/commit/25b9bea21f3d037bd42a4c3cb2a5bb1159038b3b

**Comment by ViralBShah** [comment]
Yes, that is a good starting point.
