### ISSUE TITLE
Regression

### ISSUE THREAD

**Issue by matbesancon** [JuliaSparse/SparseArrays.jl#91]
On julia 1.8.0-beta3

```julia
MethodError: no method matching mul!(::SparseArrays.SparseVector{Float64, Int64}, ::LinearAlgebra.Adjoint{Float64, SparseArrays.SparseMatrixCSC{Float64, Int64}}, ::SparseArrays.SparseMatrixCSC{Float64, Int64}, ::Bool, ::Bool)
```

The method seems present on julia 1.7 since they same tests pass.

I don't have a MRE yet, will try to find one.

**Comment by dkarrasch** [comment]
Hm, on v1.7 I get

```julia
julia> mul!(y, A, x, a, b)
ERROR: MethodError: no method matching mul!(::SparseVector{Float64, Int64}, ::Adjoint{Float64, SparseMatrixCSC{Float64, Int64}}, ::SparseMatrixCSC{Float64, Int64}, ::Bool, ::Bool)
```

In LinearAlgebra, we don't allow multiplying matrices into vectors, only when `x` is a vector, we allow it to be stored in a (vector-like) matrix `y`.

**Comment by SobhanMP** [comment]
please open again with concrete examples if any, the type does not exist in julia 1.7. one solution is to convert the third matrix to a vector (as it is likely a vector in guise) or the first one to matrix.
