### ISSUE TITLE
SparseVector help text could be more helpful

### ISSUE THREAD

**Issue by Keno** [JuliaSparse/SparseArrays.jl#97]
```
help?> SparseVector
search: SparseVector AbstractSparseVector sparsevec

  SparseVector{Tv,Ti<:Integer} <: AbstractSparseVector{Tv,Ti}

  Vector type for storing sparse vectors.
```

Should at least cover how to construct one from coordinate form, conversion from other arrays, etc. Just a few examples to answer, "how do I get one".

**Comment by ViralBShah** [comment]
@SobhanMP Since you have been visiting sparse docs, wondering if adding this would be possible?

**Comment by SobhanMP** [comment]
will do
